export const TECH_STACK_OPTIONS = [
  'React', 'Node.js', 'Express', 'MongoDB', 'PostgreSQL', 'JavaScript', 'TypeScript',
  'Python', 'Django', 'Flask', 'Java', 'Spring Boot', 'C++', 'Go', 'Rust',
  'AWS', 'Docker', 'Kubernetes', 'Firebase', 'GraphQL', 'Next.js', 'Vue.js',
  'Tailwind CSS', 'Figma', 'UI/UX Design', 'Product Management', 'Mobile Development',
  'React Native', 'Flutter', 'DevOps', 'Machine Learning', 'Data Science',
  'Angular', 'Svelte', 'Redis', 'MySQL', 'SQLite', 'Prisma', 'Supabase',
  'Socket.io', 'WebSockets', 'REST API', 'FastAPI', 'OpenAI API', 'LangChain',
  'Hugging Face', 'TensorFlow', 'PyTorch', 'Scikit-learn', 'Pandas', 'NumPy',
  'Three.js', 'WebGL', 'Electron', 'Tauri', 'Linux', 'Nginx', 'CI/CD',
  'GitHub Actions', 'Terraform', 'Solidity', 'Web3.js', 'Ethers.js', 'IPFS',
  'ChromaDB', 'Pinecone', 'OpenCV', 'Selenium', 'Playwright', 'Jest', 'Vitest',
  'PHP', 'Laravel', 'Ruby on Rails', 'Swift', 'Kotlin', 'Unity', 'C#'
].sort();

export const ROLE_OPTIONS = [
  'Frontend Developer',
  'Backend Developer',
  'Fullstack Developer',
  'UI/UX Designer',
  'Product Manager',
  'DevOps Engineer',
  'Mobile Developer',
  'Data Scientist',
  'QA Engineer',
  'Project Manager',
  'System Architect',
  'Blockchain Developer',
  // New additions
  'ML Engineer',
  'AI Engineer',
  'Cloud Engineer',
  'Security Engineer',
  'Game Developer',
  'Embedded Systems Engineer',
  'Database Administrator',
  'Technical Writer',
  'Open Source Contributor',
  'API Developer',
  'Web3 Developer',
  'AR/VR Developer',
  'Data Engineer',
  'Site Reliability Engineer',
].sort();