const express=require("express")
const app=express()
const cookieParser=require("cookie-parser")
const cors=require("cors")
app.use(cors())
app.use(express.json())
app.use(cookieParser())
const authRoutes=require("./routes/user.route")
app.use("/api/auth",authRoutes)
const projectRoutes=require("./routes/project.route")
app.use("/api/project",projectRoutes)
module.exports=app
