const mongoose=require("mongoose")
const projectSchema=new mongoose.Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true,
        trim:true
    },
    tech_stack:{
        type:[String],
        required:true,
        trim:true,
        default:[],
        validate:{
            validator:function(v){
                return v.length>0
            },
            message:"Skills are required"
        }
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    roles_needed:{
        type:[String],
        required:true,
        trim:true,
        default:[],
        validate:{
            validator:function(v){
                return v.length>0
            },
            message:"Roles are required"
        }
    },
    join_requests:[{
       user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
       },
       status:{
        type:String,
        required:true,
        enum:["pending","accepted","rejected"],
        default:"pending"
       },
       requested_at:{
        type:Date,
        default:Date.now
       }
    }],
    members:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User"
            },
            role:{
                type:String,
                enum:["frontend","backend","fullstack","ui/ux","project_manager","other"],
                default:"other"
            },
            joined_at:{
                type:Date,
                default:Date.now()
            }
        }
    ],
    removed_members:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User"
            },
            removed_at:{
                type:Date,
                default:Date.now()
            }
        }
    ],
    invitations:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:"User"
            },
            status:{
                type:String,
                enum:["pending","accepted","rejected"],
                default:"pending"
            },
            invited_at:{
                type:Date,
                default:Date.now()
            }
        }
    ]
},{timestamps:true})
const projectModel=mongoose.model("Project",projectSchema)
module.exports=projectModel