const express=require("express")
const projectControllers=require("../controllers/project.controller")
const {authmiddleware}=require("../middlewares/auth.middleware")
const {projectOwner}=require("../middlewares/project.owner")
const router=express.Router()
router.route("/create").post(authmiddleware,projectControllers.createProject)
router.route("/").get(projectControllers.getAllProjects)
router.route("/search").get(projectControllers.searchProject)
router.route("/update/:id").put(authmiddleware,projectOwner,projectControllers.updateProject)
router.route("/delete/:id").delete(authmiddleware,projectOwner,projectControllers.deleteProject)
router.route("/request/:id").post(authmiddleware,projectControllers.requestToJoinProject)
router.route("/respond/:id").post(authmiddleware,projectOwner,projectControllers.respondJoin)
router.route("/my-projects").get(authmiddleware,projectControllers.getMyProjects)
router.route("/:id").get(projectControllers.getProjectById)
router.route("/remove-member/:id").post(authmiddleware,projectOwner,projectControllers.removeMember)
router.route("/invite/:id").post(authmiddleware,projectOwner,projectControllers.inviteMember)
router.route("/respond-invitation/:id").post(authmiddleware,projectControllers.respondToInvitation)
module.exports=router